### ISSUE TITLE
request to clarify 'Bearer' vs 'bearer' in USS Spec

### ISSUE THREAD

**Issue by issmith1** [nasa/utm-apis#100]
Neither oauth2 RFC nor USS Spec explicitly state whether 'bearer' is also accepted. 

Might the USS Spec explicitly state case sensitivity?  In Sprint1 most USSs accepted insensitive, but one USS rejected small case.  See also UTM-3666

**Comment by nasajoey** [comment]
RFC6750 has the syntax with a capital 'B'.  It doesn't offer an alternative of a 'b'.  Thus that should be the spec.

https://tools.ietf.org/html/rfc6750#page-5
