### ISSUE TITLE
clarify in USS Spec - reject upon getting JSON fields not declared in the class?

### ISSUE THREAD

**Issue by issmith1** [nasa/utm-apis#102]
Kevin (Uber) [12:38 PM]
What’s the expected protocol for handling messages with unknown fields? We’re receiving operations with an extraneous user_id field

Kevin (Uber) [12:38 PM]
It looks like from Amazon

irene - NASA [1 hour ago]
I look at the latest USS spec and could not find a requirement to reject(or allow) if  the the json instance contains fields that are not declared in the class;  Long ago it was in the spec.

**Comment by nasajoey** [comment]
leaving to future sprint.

The Spec says (or said) that you can/should ignore unknown fields per JSON common practice.  I'm feeling like we should tighten down and not allow unknown fields to be exchanged.

**Comment by nasajoey** [comment]
I'm wondering about the implications of this decision.  Specifically, what if the unknown fields end up being more data than the spec fields?  This is OK?  I feel that this opens the possibility for (accidental or intentional) DOS attacks.

Also this has implications on the signatures.  You are now signing a bunch of extra fields which may be problematic (but not sure).

I assume that the receiver isn't required to store the extra fields, right?

**Comment by utmnasa** [comment]
For TCL4 we reduced UTMRestResponse from 3 to 2 fields, reasons were for data size reduction (and simplicity).

**Comment by HarryAirMap** [comment]
The receiver side does not need to store the extra fields. Simply ignoring any extra field should be good. Quite often the extra fields contain values for internal test, e.g. we have assigned a code to each individual error for bad requests or forbidden requests, and add an extra field "code" to the http response of 400, 403 or 404. e.g. the http response will look like {"http_status_code":403,"message":"no right scope in the token","code":202}. In our internal integration tests, the code helps us quickly identify what exact error it is.

**Comment by utmnasa** [comment]
We have a similar code strategy but we embed it in the 'message' field.

**Comment by HarryAirMap** [comment]
May I suggest keep a balance between convenience and  strictness? e.g. always allow 1 extra field, if the number of required fields are 5, then set the check to 6.

**Comment by issmith1** [comment]
Another option is to add an Optional field ONLY to UTMRestResponse.
It can be of  type int or int[] array of  a small max size.

**Comment by issmith1** [comment]
Section 8 of USS Spec says
"For any exchange of JSON-formatted data, the receiver MAY ignore any fields that are supplied by the sender that are not included in the relevant schema definition."

thus Tcl4valtest has a bug in that it disallows an extra field in UTMRestResponse.

**Comment by nasajoey** [comment]
I know this is closed, but for historical completeness, I'd like to provide references that illustrate where the thinking that unknown fields should be disallowed.  I still feel that in the long term for an operational UTM System, that USSs must conform to a spec such that no unrecognized fields are allowed.

This is supported by NASA Secure Coding Practices:

> SCP-67: Assume all input is malicious. Use an "accept known good" input validation strategy, such as a whitelist of acceptable inputs that strictly conform to specifications. Reject any input that does not strictly conform to specifications or transform it into something that does.

There are other NASA SCPs as well that support rejecting input that is not to spec, but this one is sufficient to illustrate the issue.

Likewise, OWASP has the following guidance:

>  Validate for expected data types
>  Validate data range
>  Validate data length

Granted these are all open to some interpretation, but the strictest reading of this would imply that unexpected data (like extra JSON fields) should invalidate the input completely.  I think this is the approach that UTM will need in the long term, but that is at odds with current research goals.  Thus, it makes sense to fallback on the JSON best practice of just ignoring unknown fields for now so we can actually do work and advance the concept.

**Comment by nasajoey** [comment]
OWASP reference: https://www.owasp.org/images/0/08/OWASP_SCP_Quick_Reference_Guide_v2.pdf
