### ISSUE TITLE
Maximum Email Address Length

### ISSUE THREAD

**Issue by esparano** [nasa/utm-apis#104]
One of the automated validation tests verifies that we accept 500-character emails. I feel that there should be a much lower limit on the length of emails. The theoretical maximum number of characters is 254, and from what I've seen the practical maximum is around 100. 
See https://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address
for relevant discussion and some links to relevant RFCs.

Additionally, the SwaggerHub specs do not specify a minLength or a maxLength for the email addresses in the email_addresses field. 

#91 may be relevant.

**Comment by nasajoey** [comment]
Thanks.  Done.
