### ISSUE TITLE
Can two consecutive OperationVolumes have same effective_time_begin?

### ISSUE THREAD

**Issue by punamverma** [nasa/utm-apis#105]
@nasajoey I want to clarify whether two consecutive OperationVolumes of an Operation, can have the same effective_time_begin? Or, does the effective_time_begin of second OperationVolume needs to be greater than the effective_time_begin of the previous OperationVolume?

**Comment by nasajoey** [comment]
see #39 .    Yes, those times can be equal.

b. When ordered by ordinal values, a succeeding operation volume
              must have a non-negative temporal intersection with its
              immediately preceding operation volume (Note we'd calculate this
              by t1-t2 where t1 is the preceding operation volume end time and
              t2 is the succeeding operation volume start time.).
