### ISSUE TITLE
UtmCommons - PriorityElements - further develop the concept to know exactly when to apply which severity level

### ISSUE THREAD

**Issue by issmith1** [nasa/utm-apis#11]
This task will not be scheduled until post TCL3 event.

we should have a separate ticket to further develop the concept to know exactly when to apply which severity level

**Comment by nasajoey** [comment]
Internal emails circulating on this topic.  If any external folks have ideas/comments, now is a good time and here is a good place.

**Comment by issmith1** [comment]
@nasajoey  did 100% coverage.  WOW
