### ISSUE TITLE
example data is authz's swagger spec is out of date

### ISSUE THREAD

**Issue by issmith1** [nasa/utm-apis#110]
example:
      access_token: tokenstring
      token_type: bearer
      expires_in: 3599
      scope: utm.nasa.gov_write.operation utm.nasa.gov_read.operation  # del read op
      sub: nasaUSS ## should be like "nuss1.testing.nasa.gov"
      nbf: 1509470774
      iss: fims.arc.nasa.gov/fimsAuthServer
      jti: 4d4c1a63-0959-48cc-885a-3648fd582db7

**Comment by nasajoey** [comment]
@issmith1 does this example still reflect what the auth server produces as an access_token?  I feel like the auth server may be adding in additional fields?  can you confirm/deny my feelings?

**Comment by issmith1** [comment]
this is its payload

{
  "sub": "utmalpha.arc.nasa.gov",
  "nbf": 1554437654,
  "scope": [
    "utm.nasa.gov_write.operation"
  ],
  "iss": "fims.arc.nasa.gov/fimsAuthServer",
  "exp": 1554441254,
  "jti": "4bad133a-2054-4e26-9eb6-1ed9a64c6db1",
  "client_id": "utmalpha.arc.nasa.gov"
}

**Comment by issmith1** [comment]
we thought of adding 'aud' but that is yet an open issue.  

We look at 'sub'.  With our framework I needed to grab 'sub' from the   http-request-filter-chain so it can be checked in our webapp.
