### ISSUE TITLE
Add 423 response to /operations/{gufi} in uss-api

### ISSUE THREAD

**Issue by ktian94** [nasa/utm-apis#112]
For Sprint 2, we need to be able to return the 423 status code for /operations/{gufi} when the caller is requesting an operation that has been put to the grid but not yet committed. Confirmed with @myspri in Slack that this is the endpoint used to fetch flight volumes when deconflicting. cc: @nasajoey @hi-kevin

**Comment by nasajoey** [comment]
Made the fix in v4-draft-dev.  Please review for correctness.  If I get a couple thumbs up, will close.

**Comment by nasajoey** [comment]
Assuming good... closing.

**Comment by myspri** [comment]
@nasajoey, here is a comment
https://github.com/nasa/utm-apis/commit/315d71cd49e9ef196c58c1394686e99ea8e1660a

    On Tuesday, October 9, 2018, 7:05:28 AM PDT, Joseph Rios <notifications@github.com> wrote:  
 
 
Closed #112.
