### ISSUE TITLE
As an USS, I need a new state to indicate that my Operation is under planning

### ISSUE THREAD

**Issue by myspri** [nasa/utm-apis#117]
An operation with large volumes that span multiple grids can a take a while before get ACCEPTED.

GET /operation end point returns a list of operations along with the state info. 
We need a state to indicate that the operation is still being planned.

Should "PROPOSED" be a valid state?

**Comment by nasajoey** [comment]
Added state in Operation model.  Will hold off on larger protocol uses at the moment.  Will close this for now...  how to use this state (if at all in Sprint 3) will be provided elsewhere I think.
