### ISSUE TITLE
Remove pathitems in utm commons

### ISSUE THREAD

**Issue by nasajoey** [nasa/utm-apis#120]
Unclear if the pathitems element in utm commons is needed.  If not needed, should remove.  Tagging @punamverma and @issmith1 to verify the need.

**Comment by issmith1** [comment]
Should be removed.  

Not sure when it was introduced but it serves no purpose.  To codegen a 'Version' model, we need to trigger via an API;  the OPS API https://app.swaggerhub.com/apis/utm/fims/v4 defines /api endpoint which triggers the codegen of the 'Version' model into our utm-commons model library.

**Comment by nasajoey** [comment]
Thanks @issmith1 .  Done.
