### ISSUE TITLE
Do we need NegotiationAgreement.message_id?

### ISSUE THREAD

**Issue by jeremie-leproust** [nasa/utm-apis#129]
https://github.com/nasa/utm-apis/blob/b78492020d31172c258be459c623535209ccf116/utm-domains/utm-domain-commons.yaml#L1451
Do we need message_id in the negotiation agreement, or is negotiation_id sufficient in this context?
In case we support negotiations later with multiple messages, which one should we use here?

**Comment by nasajoey** [comment]
Negotiations are linked now through negotiations_id, however each message that is exchanged is unique and needs a message_id.  Same with NegotiationAgreement... it can reference the full exchange of messages through the negotiation_id, but the NegotiationAgreement itself is potentially a stand alone message, so I think we want the message_id.

**Comment by jeremie-leproust** [comment]
Got it :)
