### ISSUE TITLE
referencePoint query parameter should be consistent across all UTM-APIs

### ISSUE THREAD

**Issue by issmith1** [nasa/utm-apis#13]
UTM-3219 | This task will be scheduled post TCL3 event.Currently, the public safety /uas/operations and uss /operations Swagger documentation have the referencePoint query parameter as a String specified as a GeoJson, whereas the discovery version of referencePoint is a List<Double>. (Might need to look at the versions on GitHub rather than SwaggerHub).For the time being, we can code them as written is Swagger despite their differences, but ultimately, these should be the same across the board. I recommend that they all be List<Double> as submitting a GeoJson string in a URL can be problematic.
-- | --

**Comment by alotau** [comment]
Would be great to get comments from implementers on which approach to standardize upon.

**Comment by nasajoey** [comment]
I'm leaning toward the geojson.  We provide URL-safe examples of the reference point being a geojson point (2D).

Also preferring this solution since the discovery API might be a candidate for a general overhaul.

**Comment by nasajoey** [comment]
Done unless anyone yells loudly enough.
