### ISSUE TITLE
Add NegotiationMessage.discovery_reference?

### ISSUE THREAD

**Issue by jeremie-leproust** [nasa/utm-apis#131]
https://github.com/nasa/utm-apis/blob/b78492020d31172c258be459c623535209ccf116/utm-domains/utm-domain-commons.yaml#L1532

Should we add a discovery_reference required field for the negotiation requester?

**Comment by nasajoey** [comment]
added discovery_reference as an optional field for now.  can be used in protocols if we need it.  if it turns out we need it all the time, then we'll switch to required.
