### ISSUE TITLE
Callback URL needs to be mandatory

### ISSUE THREAD

**Issue by sjurcak** [nasa/utm-apis#136]
Since discovery_reference is no longer required, there is no easy way to find the callback. Given that there are two possible solutions for Discovery, one might fallback to the old Discovery model, and not pass a discovery_reference. In this case, it would be impossible to contact the USS.

**Comment by nasajoey** [comment]
Is it required with all UTMMessages?  Or just for PERIODIC_POS_REP_START messages?  Spec already notes it is required in that case.

**Comment by nasajoey** [comment]
talked with @myspri and made changes.  Closing for now... if still needs fixing, reopen with comments.
