### ISSUE TITLE
contingency_plans in Operations is not required, but min length is 1

### ISSUE THREAD

**Issue by sjurcak** [nasa/utm-apis#137]
Operations does not require contingency_plans, but the minimum length of the array is 1.

**Comment by issmith1** [comment]
when this  is resolved please assign to UTM Software so the workaround is removed.

**Comment by nasajoey** [comment]
Just to clarify, this is two different issues, one of which is invalid.

1:  We actually want contingency_plans to be required.  Will make this edit.
2:  When an array field is not required AND has minItems > 0, this is not a problem.  If the field is not included, then its length is not checked.  Analogy to optional string that have minLength > 0.  If the element is not included, then its length is not checked.

**Comment by nasajoey** [comment]
contingency plans will be required as of sprint 4.
