### ISSUE TITLE
Need to define rules for operation volume intersection

### ISSUE THREAD

**Issue by myspri** [nasa/utm-apis#14]
USS-API needs to define the rules for volume intersection. Should the adjacent 4D volumes be overlapping/touching?

**Comment by nasajoey** [comment]
Will slowly add notes here prior to editing the api/models.  Welcome feedback on these suggestions.

I'll label each business rule for operation volume intersections as 'op_vol_rule_num' so that we can refer to them in this discussion chain if necessary.

I am not going to provide these in any particular order.  There may be discrepancies/conflicts in these suggested rules.  We will likely need some sort of precedence in checking some of these rules, but unclear as of now.

**Comment by nasajoey** [comment]
**op_vol_rule_1**: The array of operation volumes must have minimum length of 1.
**op_vol_rule_2**: Each operation volume must have non-zero 4D volume (i.e. each of the 4 dimensions much be > 0 in magnitude).
**op_vol_rule_3**: When ordered by ordinal values, a succeeding operation volume must have a non-zero 4D intersection with its immediately preceding operation volume (i.e. there must be intersection in 3D space and in time).  Note:  in the future there may be more detailed requirements in terms of a minimum 4D intersection, but for now "> 0" is good enough.
**op_vol_rule_4**: if ordinal_a < ordinal_b, then begin time of a < begin time of b and end time of a < end time of b.  Note: we can discuss if these should be strictly less than vs less then or equal to.

**Comment by nasajoey** [comment]
**op_vol_rule_5**: The array of operational volumes must have length no greater than N.  Should discuss with partners the value of N.  Considerations here relate to exchangeability of data due to size and the ability to efficiently perform checks against the array of op vols... the more there are the more potentially expensive calculations need to be made by the receiver of the data.

**Comment by nasajoey** [comment]
**op_vol_rule_6**: Each side of an op vol's bounding box must have length less than M.  Should discuss with partners the value of M.  This is a sanity check against excessively large volumes.  Need to be careful here as there may be legitimate use cases wherein large volumes are required/allowed, but we want to encourage efficient planning and protect against misuse of the shared airspace.

**Comment by nasajoey** [comment]
**op_vol_rule_7**: The planned duration of an op vol must be less than T.  Again, need to be careful to not damage legitimate use cases, but need to protect against misuse/poor planning.  For long duration missions, it may be reasonable to have them replan or to have volumes with the same geog and long time values that slightly intersect.

**Comment by esparano** [comment]
For op_vol_rule_3, why must consecutive operation volumes have a 4D intersection? Is "barely touching" in 3D space but overlapping in time not sufficient? The overlap in time gives some room to transition between consecutive operation volumes. It seems reasonable to me that an overlap in space but just "barely touching" in time would be another valid way to transition between operation volumes.

**Comment by nasajoey** [comment]
Can you define "barely touching"? That will help me think and respond.

**Comment by esparano** [comment]
Well I was just thinking that if two consecutive operation volumes are rectangular prisms, and they overlap in time, then having the "ending" plane of one touch the "starting" plane of the other would be okay. 

Let's say there is only one spacial dimension for simplicity so I can just demonstrate. You could have two bounding volumes overlap in time but not in space:
volume 1: (x_start = 0, x_end = 10, t_start = 0, t_end = 10)
volume 2: (x_start = 10, x_end = 20, t_start = 5, t_end = 15)

Or you could have them overlap in space but not in time:
volume 1: (x_start = 0, x_end = 10, t_start = 0, t_end = 10)
volume 2: (x_start = 5, x_end = 15, t_start = 10, t_end = 20)

Would either of these methods of defining bounding volumes be acceptable under op_vol_rule_3? There is no 4D intersection.

**Comment by nasajoey** [comment]
I see.  So there is a spatial and a temporal overlap, but the spatial overlap is 2-dimensional (in 3D space).  Does that sound like what you are getting at?  If so, I think we can indeed clean up the language in rule 3.

**Comment by esparano** [comment]
Yeah, that's case 1. It's not so much an "overlap" as a shared boundary.

**Comment by nasajoey** [comment]
@esparano please comment on the below.  This became a bit more involved, but I think it looks more correct.

**op_vol_rule_3a**: When ordered by ordinal values, a succeeding operation volume must have a non-zero _spatial_ intersection with its immediately preceding operation volume. (Note the intersection may be 2-dimensional in 3D space, i.e. sharing a face.  Need to discuss if the intersection can be even lower dimensional.  I don't think it can reasonably be an intersection at an edge or vertex only.  Assuming all of these comments are valid, will potentially need to incorporate into this rule). 

**op_vol_rule_3b**: When ordered by ordinal values, a succeeding operation volume must have a non-negative temporal intersection with its immediately preceding operation volume (Note we'd calculate this by t1-t2 where t1 is the preceding operation volume end time and t2 is the succeeding operation volume start time.). 

**op_vol_rule_3c**: When ordered by ordinal values, a succeeding operation volume must have either a non-zero volume intersection OR a positive temporal intersection.
 
Note: Happy to take suggestions on re-wording.  This is my first cut at addressing @esparano comments above.

Note 2: All of the terms "crosses", "within", "touches" imply intersection.  I can track down a source for this definition (probably OGC), but for now, you can see it illustrated in the description for PostGIS intersection: https://postgis.net/docs/ST_Intersects.html

**Comment by esparano** [comment]
Looks good! I agree that a 2D spatial intersection is the minimum that allows an uninterrupted transition between consecutive volumes. It depends on your definition of "intersection" in space and time, so it's good to clarify that. Thanks!

**Comment by nasajoey** [comment]
I think that op_vol_rule_3c replaces op_vol_rule_4.

**Comment by nasajoey** [comment]
Will open separate ticket to track values of M and T (max bounding box edge length and max operation duration, respectively).

**Comment by nasajoey** [comment]
Going with this Operation.operation_volumes description:

      operation_volumes:
        description: >-
          The actual geographical information for the operation.

          A note on "intersection":
            Note 2: All of the terms "crosses", "within", "touches" imply 
            intersection. I can track down a source for this definition 
            (probably OGC), but for now, you can see it illustrated in the 
            description for PostGIS intersection: 
              https://postgis.net/docs/ST_Intersects.html

          Validation of the array must include the following checks:
            1. The array of operation volumes must have minimum length of 1.
            2. The array of operation volumes must have maximum length of 250.
            3.  Each operation volume must have non-zero 4D volume (i.e. each of
             the 4 dimensions much be > 0 in magnitude).
            4. Volume intersection must pass the following checks:
              a. When ordered by ordinal values, a succeeding operation volume
              must have a 2D or 3D spatial intersection with its immediately 
              preceding operation volume.
              b. When ordered by ordinal values, a succeeding operation volume 
              must have a non-negative temporal intersection with its 
              immediately preceding operation volume (Note we'd calculate this 
              by t1-t2 where t1 is the preceding operation volume end time and 
              t2 is the succeeding operation volume start time.).
              c. When ordered by ordinal values, a succeeding operation volume 
              must have either a non-zero volume (3D) intersection OR a positive
              temporal intersection. (Note it may have both intersection types.)
            5. Each spatial dimension of an op vol's bounding box must have 
            length less than M. Should discuss with partners the value of M. 
            This is a sanity check against excessively large volumes. Need to 
            be careful here as there may be legitimate use cases wherein large 
            volumes are required/allowed, but we want to encourage efficient 
            planning and protect against misuse of the shared airspace.
            6. The planned duration of an op vol must be less than T. Again, 
            need to be careful to not damage legitimate use cases, but need to 
            protect against misuse/poor planning. For long duration missions, 
            it may be reasonable to have them replan or to have volumes with 
            the same geog and long time values that slightly intersect.

**Comment by nasajoey** [comment]
Closing.  Not 100% confident the current descriptions are bug-free, but they are more complete than previously defined.  Suggest opening new issues as needed to address any changes/additions.  See Issue #39 for further discussion on some parameters that are TBD.
