### ISSUE TITLE
Sorry, we can't find utm / uss / v4

### ISSUE THREAD

**Issue by shortwavedave** [nasa/utm-apis#164]
Have the api specs moved off of swagger hub? I get this error when trying to access any of the specs on https://app.swaggerhub.com/organizations/utm

for example: https://app.swaggerhub.com/apis/utm/uss/v4

![image](https://user-images.githubusercontent.com/22798574/67311397-b9d0ab00-f4bc-11e9-9076-53f9ccbfdd0e.png)

**Comment by nasajoey** [comment]
We ended our subscription on swagger hub, and consider the github repository the current truth for the NASA UTM APIs.

**Comment by nasajoey** [comment]
Note, we've found that editor.swagger.io provides good functionality for web-accessible documentation in the short term:

http://editor.swagger.io/?url=https://raw.githubusercontent.com/nasa/utm-apis/master/uss-api/swagger.yaml

you can replace that url target parameter with any raw version of the APIs that find here on github.

**Comment by shortwavedave** [comment]
thanks @nasajoey
