### ISSUE TITLE
Allow request for multiple scopes

### ISSUE THREAD

**Issue by nasajoey** [nasa/utm-apis#173]
https://github.com/nasa/utm-apis/blob/1c4f999a8d96588ffec7c73654c10605490c8986/fimsauthz-api/fims-authz.yaml#L62

We need to allow for and array of scopes to be requested to support UPP2.0 activities.

Will file a separate ticket related to validating the allowable combinations of scopes that can be requested/granted.

**Comment by nasajoey** [comment]
maybe @issmith1 is already taking this.

**Comment by issmith1** [comment]
https://github.com/nasa/utm-apis/commit/4260051071f0f7b5d8dfc6bd3d4a0b30c869fdfb
Spec changed.
This implementation of this spec is tracked internally via UAMX3-456
