### ISSUE TITLE
Add documentation to API spec regarding limits to scope requests

### ISSUE THREAD

**Issue by nasajoey** [nasa/utm-apis#174]
Following #173 we need to specify which groups of scopes are valid to request.  We wish to limit the groups to only those which are valid to request to maintain least privilege.

Will have to obtain the groupings from team.  I think there is only one valid pairing (RID regular and RID enhanced), otherwise all requests should be single scoped.

**Comment by issmith1** [comment]
Spec changed- service implementation via UAMX3-456

**Comment by issmith1** [comment]
https://github.com/nasa/utm-apis/blob/4260051071f0f7b5d8dfc6bd3d4a0b30c869fdfb/fimsauthz-api/fims-authz.yaml#L70
