### ISSUE TITLE
Example Contingency model times should be different

### ISSUE THREAD

**Issue by esparano** [nasa/utm-apis#22]
The example requests/responses for the following endpoints:

- PUT /utm_messages/{message_id}
- GET /operations
- GET /operations/{gufi}
- PUT /operations/{gufi}

contain one or more "contingency" objects which have identical begin and end times.

> "valid_time_begin": "2015-08-20T14:31:56.118Z",
> "valid_time_end": "2015-08-20T14:31:56.118Z"

The end time should be after the begin time, unless I'm misunderstanding something.

**Comment by nasajoey** [comment]
You are understanding.  Maybe a little too well.

**Comment by nasajoey** [comment]
Single fix in the commons domain.  Updated end time example to be after begin time.
