### ISSUE TITLE
PUT vs POST consistency

### ISSUE THREAD

**Issue by esparano** [nasa/utm-apis#23]
Throughout the docs, there seems to be an alternation between PUT and POST. For example, the PUT negotiations/{message_id} endpoint's description reads: 

> A POST to the negotiations endpoint is interpretted as a request for alteration in an existing operation managed by the receiving USS

(interpreted is misspelled by the way)

There are a few other places too such as the description of /utm_messages/{message_id} and in /operations/{gufi}

**Comment by nasajoey** [comment]
This is a known issue.  The descriptions are outdated.  The endpoints are correct.  Will leave this open until we address.  Thanks for making the note.

**Comment by nasajoey** [comment]
Cleaning house.  Fixed the ones I found in the USS API.  If this issue exists in other APIs, either re-open or start a new issue.
