### ISSUE TITLE
Invalid Default Sort for Operations

### ISSUE THREAD

**Issue by esparano** [nasa/utm-apis#32]
The USS Required API "GET /operations" endpoint on SwaggerHub indicates that the "sort" parameter has a default value of "time_submitted", but "time_submitted" is not a valid field of an Operation. It seems like it should be "submit_time".

**Comment by nasajoey** [comment]
Good catch.  The field names changed, but the documentation for sorting did not.  Will fix.

**Comment by nasajoey** [comment]
Linking with Issue #34 .

**Comment by nasajoey** [comment]
@drsmit22 , assigning the two of us to this.
