### ISSUE TITLE
Operation Sorting Description

### ISSUE THREAD

**Issue by esparano** [nasa/utm-apis#34]
I have a few questions about sorting operations, so I figured I'd make an issue in case the documentation needs to be cleared up.

The USS Required API "GET /operations" endpoint on SwaggerHub indicates that the "sort" parameter can be "A valid field name to use for sorting records".

1) If you're sorting by a non-required field such as "last_lun_update_time", some operations may not have a value specified for that field. Should I sort with "nulls first" or "nulls last"? If in ascending order, I'm putting operations with null last_lun_update_time last. Descending order is the opposite, with nulls first.

2) What exactly defines a "valid field name"? Some fields make sense to sort on, while others like controller_location or operation_volumes do not, for example.

3) When sorting on an enum value such as operation "state", I define ascending order to match the order of the enum values as defined in the Operation model documentation, [ ACCEPTED, ACTIVATED, CLOSED, NONCONFORMING, ROGUE ]. Is that correct?

4) Similar to question 3, I don't really know what "ascending" or "descending" means for each field. For example, different libraries or databases sort UUIDs in very different ways.

5) Should it be possible to sort on sub-fields like metadata or priority_elements, and if so, what would such a GET request look like? For example, it could be useful to sort on metadata.event_id or metadata.test_type.

Thanks!

**Comment by nasajoey** [comment]
@drsmit22 assigned this to the two of us.  We can discuss offline or here.

**Comment by nasajoey** [comment]
@esparano , let me know what you think of these two commits.  I think I hit everything.

**Comment by esparano** [comment]
I'm still unclear on what the "most significant field" means for a UUID. Are you saying to compare the given UUID basically as a simple string, left to right, 1 letter/digit at a time, until a difference is found? Here's a snippet from Wikipedia detailing what I was getting at earlier:
![image](https://user-images.githubusercontent.com/3947139/42526208-33095030-8443-11e8-99a4-abd58af029d6.png)

**Comment by esparano** [comment]
I think everything else looks good. Question 1 seems to be irrelevant now because the fields that can be sorted on happen to be required.
