### ISSUE TITLE
Example Model Inconsistencies

### ISSUE THREAD

**Issue by esparano** [nasa/utm-apis#35]
A couple small inconsistencies in the models from the USS Required API:

1) UasRegistration registration_id should be a UUID, not "string"
2) A ContingencyPlan's"valid_time_end" should be a time after "valid_time_begin", not equal to it
3) NegotiationMessage "message_id", "gufi_of_originator", "gufi_of_receiver", and "reference_message_ids" should be UUIDs, not "string"

**Comment by nasajoey** [comment]
Going to close.  For 1 & 3 in your list, the type is "string" and the format is "uuid" as per OpenAPI spec.  For 2, I think I hit that in another issue already.

Please correct me if I'm mistaken on any of this.

**Comment by esparano** [comment]
"string" is fine, but many other example models do put a real UUID like "00000000-4444-8888-FEEDDEADBEEF" for fields that are "uuid" strings. It seemed inconsistent across models and even within the same model, and when I tried copy-pasting the example request and using it in our system, it failed multiple validation checks for that reason. Not a huge deal though, so up to you guys whether you want to change it!
And yes, #2 was a duplicate. I forgot I submitted that already.

**Comment by nasajoey** [comment]
If the model is wrong, we should fix.  I haven't caught any of the inconsistencies you mention, but that doesn't mean they aren't there.

The goal is to follow OpenAPI spec 2.0 which has this guidance (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md):

> Primitive data types in the Swagger Specification are based on the types supported by the JSON-Schema Draft 4. Models are described using the Schema Object which is a subset of JSON Schema Draft 4.
> 
> An additional primitive data type "file" is used by the Parameter Object and the Response Object to set the parameter type or the response as being a file.
> 
> Primitives have an optional modifier property format. Swagger uses several known formats to more finely define the data type being used. However, the format property is an open string-valued property, and can have any value to support documentation needs. Formats such as "email", "uuid", etc., can be used even though they are not defined by this specification. Types that are not accompanied by a format property follow their definition from the JSON Schema (except for file type which is defined above). The formats defined by the Swagger Specification are:
> 
> Common Name | type | format | Comments
> -- | -- | -- | --
> integer | integer | int32 | signed 32 bits
> long | integer | int64 | signed 64 bits
> float | number | float |  
> double | number | double |  
> string | string |   |  
> byte | string | byte | base64 encoded characters
> binary | string | binary | any sequence of octets
> boolean | boolean |   |  
> date | string | date | As defined by full-date - RFC3339
> dateTime | string | date-time | As defined by date-time - RFC3339
> password | string | password | Used to hint UIs the input needs to be obscured.
>

**Comment by esparano** [comment]
Ah sorry if I wasn't clear. The model is correct, but some examples seem inconsistent. For example,
![image](https://user-images.githubusercontent.com/3947139/41125407-6002b396-6a72-11e8-8b0c-eb6a2d99e003.png)
versus the example:
![image](https://user-images.githubusercontent.com/3947139/41125447-7b909970-6a72-11e8-861a-a28f789618aa.png)
One "uuid" field is "string", and the other is "00000000-4444-8888-FEEDDEADBEEF". Again, not super important but I figured it would be worth at least bringing up.

**Comment by nasajoey** [comment]
Ah, I see.  I think this is default behavior of the swagger tools.  Probably what is happening is that there is not actually an explicit example for that data field (message_id) and the tool puts in "string" for the value when trying to complete an example instance.

OK, so the ticket should actually be "ensure there is a reasonable example for data fields".

**Comment by esparano** [comment]
Oh okay, that makes sense. I wasn't aware of how the Swagger tools work. Yeah, that would have been a better title.
