### ISSUE TITLE
Polygon coordinate array min/max wrong

### ISSUE THREAD

**Issue by nasajoey** [nasa/utm-apis#38]
Looks like polygon coordinate should be min and max number of elements equal to 2, but currently 1.

Why was this OK with everyone for so long?  Am I missing something?

**Comment by myspri** [comment]
Are we going to allow more volumes for operations those that are of type TBOV?

**Comment by nasajoey** [comment]
As of now, there is not a need/requirement for varying the max number of volumes for any reason.  We'll see if that changes... I do agree that you'll probably have more volumes when exercising TBOVs.
