### ISSUE TITLE
Max bounding box edge length and max operation duration

### ISSUE THREAD

**Issue by nasajoey** [nasa/utm-apis#39]
Based on Issue #14:

What is a reasonable value for the max bounding box edge length for a single operation volume?

What is a reasonable value for an operation's maximum duration?

Should we even have such limits?

How does dynamic replanning affect these values (e.g. replanning an active operation to increase duration)?

Please comment below.

**Comment by nasajoey** [comment]
Addressed temporarily #63 .

**Comment by rstrauss-logyx** [comment]
Based on our discussions, Joey, 
- 6000 feet is the maximum length of a bounding box side 
- 2 hours is the maximum duration of a flight

These are reflected in lines 15 & 16 of the spreadsheet [TCL4 USS Dev: Strict Validation](https://docs.google.com/spreadsheets/d/1TJu4O9CI3BUXc_tGfcMTPYBzs0flSHQVwO5gYMmRRDQ)

**Comment by nasajoey** [comment]
Leaving as-is from SPrint 1:

operation_volumes:
        description: >-
          The actual geographical information for the operation.

          A note on "intersection":
            Note 2: All of the terms "crosses", "within", "touches" imply
            intersection. I can track down a source for this definition
            (probably OGC), but for now, you can see it illustrated in the
            description for PostGIS intersection:
              https://postgis.net/docs/ST_Intersects.html

          Validation of the array must include the following checks:
            1. The array of operation volumes must have minimum length of 1.
            2. The array of operation volumes must have maximum length of 250.
            3.  Each operation volume must have non-zero 4D volume (i.e. each of
             the 4 dimensions much be > 0 in magnitude).
            4. Volume intersection must pass the following checks:
              a. When ordered by ordinal values, a succeeding operation volume
              must have a 2D or 3D intersection in 3D space with its immediately
              preceding operation volume.  Note that a 2D intersection in 3D
              space implies two volumes that "touch" and the intersection has 2D
              area.  Sharing just an edge would not qualify.  3D volumes that
              don't touch at all would not qualify, even if they would intersect
              when projected into 2D space (e.g. if "looking down" on the two
              volumes).
              b. When ordered by ordinal values, a succeeding operation volume
              must have a non-negative temporal intersection with its
              immediately preceding operation volume (Note we'd calculate this
              by t1-t2 where t1 is the preceding operation volume end time and
              t2 is the succeeding operation volume start time.).
              c. When ordered by ordinal values, a succeeding operation volume
              must have either a non-zero volume (3D) intersection OR a positive
              temporal intersection. (Note this is a logical "OR" so it may have
               both intersection types... i.e. it is not an "exclusive OR").
            5. Each spatial dimension of an op vol's bounding box must have
            length less than 6000ft (should discuss with partners this value).
            This is a sanity check against excessively large volumes. Need to
            be careful here as there may be legitimate use cases wherein large
            volumes are required/allowed, but we want to encourage efficient
            planning and protect against misuse of the shared airspace.
            6. The planned duration of an op vol must be less than 120 minutes. Again,
            need to be careful to not damage legitimate use cases, but need to
            protect against misuse/poor planning. For long duration missions,
            it may be reasonable to have them replan or to have volumes with
            the same geog and long time values that slightly intersect.
            7. The start time of an operation volume other than the first in the
            array must be greater than or equal to the start time of its
            immediately preceding operation volume.
            (note this probalby should be #4 or so, bumping the others down,
            but I didn't want to cause confusion in case implementers are
            referencing these checks somewhere by number.)

**Comment by nasajoey** [comment]
To correct @rstrauss-logyx above... 120 mins is the limit for a single volume, not the entire operation.
