### ISSUE TITLE
timestamp max length should be 24?

### ISSUE THREAD

**Issue by nasajoey** [nasa/utm-apis#42]
All timestamps currently have a maxLength of 25.  Recounting, it seems like 24 is correct value since we allow at most ms precision.

Looking for confirmation from anyone else before making mass change to all timestamps.  Counting is not my strong suit.

**Comment by nasajoey** [comment]
@issmith1 , @myspri , @punamverma , @sjurcak can you comment on this issue?  I need a sanity check.

**Comment by punamverma** [comment]
@nasajoey you are right maxlength can be made 24.

**Comment by nasajoey** [comment]
Thanks @punamverma , made the change.  Closing.
