### ISSUE TITLE
Query instances from USS-Disc returns only 10 instances by default

### ISSUE THREAD

**Issue by myspri** [nasa/utm-apis#47]
During startup, USSs are expected to query Disc to make their LUN.
By returning only 10 instances by default, USSs might miss the rest that could potentially be in the LUN.

This was one of the problems that we identified during TCL3 checkout.

**Comment by nasajoey** [comment]
Understood.  Will hold off on Disc discussions for a couple weeks.  Keeping open until then at least.

**Comment by nasajoey** [comment]
Fixing this even though discovery may be changing.  Want to clear out issues.
