### ISSUE TITLE
Remove resource field in UTMRestResponse

### ISSUE THREAD

**Issue by ktian94** [nasa/utm-apis#52]
The NASA USS does not consume the resource field in UTMRestResponse nor has it been used in testing events. Can we remove it from the spec?

**Comment by myspri** [comment]
Here is a sample 400 error message 
{
  "http_status_code": "400",
  "message": "Error message",
  "resource": "/resource/683c0e9e-49dc-44ce-82de-a5723b1f6965"
}

**Comment by nasajoey** [comment]
There was an original intent with this field.  It was supposed to point the caller to something.  Do you recall why we added this in the first place?

**Comment by nasajoey** [comment]
Was this in place back with "UTM Core" would create your GUFI for an operator directly?  The 'resource' was a convenience for the operator's client system to easily build request for the new operation.  If this history sounds correct, I agree that it can be removed.  Will wait for confirmation from @myspri , @drsmit22 , or @issmith1 .

**Comment by myspri** [comment]
Yes, it can be removed.

**Comment by myspri** [comment]
Yes, it can be removed.

**Comment by myspri** [comment]
Yes, both will be needed. Helps the caller know details about the exception

**Comment by nasajoey** [comment]
@ktian94 thanks for the report.  pushed change to v4-draft branch.  re-open or open a new one if I missed something.
