### ISSUE TITLE
Clarification on last_lun_update_time field requirement

### ISSUE THREAD

**Issue by boguwei** [nasa/utm-apis#57]
Three questions regarding the `last_lun_update_time` field of the `Operation` model 

1. The description states that "this field MUST reflect the time the update was provided". Does this mean that this field is a required field for the Operation? It is not in the `required` properties section. (ref: [file here](https://github.com/nasa/utm-apis/blob/cf4211d5d8119813aca17d87a8e97f5afbe7768c/utm-domains/utm-domain-commons.yaml#L160))

2. The description also makes reference of a `last_submitted_update_time` property, which is not mentioned anywhere else in the model. Is this an old name of the same property, which name should we be using for the property name? (ref: [file here](https://github.com/nasa/utm-apis/blob/cf4211d5d8119813aca17d87a8e97f5afbe7768c/utm-domains/utm-domain-commons.yaml#L160))

3. The `minItems` on the list of `contingency_plans` is 1, but `contingency_plans` is not a field from the `required` section, so shouldn't the minimum items list be size 0? (ref: [file here](https://github.com/nasa/utm-apis/blob/cf4211d5d8119813aca17d87a8e97f5afbe7768c/utm-domains/utm-domain-commons.yaml#L288))

4. The maximum items allowed for list of `uas_registrations` does not match what is specified in the model validation checkout spreadsheet provided by Joey for TCL4 Sprint 0. The API specifies 1000, but the spreadsheet specifies 100. (ref: [file here](https://github.com/nasa/utm-apis/blob/cf4211d5d8119813aca17d87a8e97f5afbe7768c/utm-domains/utm-domain-commons.yaml#L208))

**Comment by nasajoey** [comment]
Going to relax on this one until discovery in general is further discussed.

**Comment by nasajoey** [comment]
I think most of these addressed?  Closing out.  Please reopen if something is still lingering.
