### ISSUE TITLE
ConstraintMessage::permitted_guifs length says 0-100 for each gufi

### ISSUE THREAD

**Issue by mcelhennyi** [nasa/utm-apis#62]
The ConstraintMessage::permitted_guifs length says 0-100 for each gufi, is this correct or should it be 36 instead like other gufis?

**Comment by nasajoey** [comment]
Good catch.  this should be minItems/maxItems and should be describing the array, not the individual GUFIs.  the indenting is off as well as the label names.  Will fix after Sprint 0.

**Comment by nasajoey** [comment]
just making a note for myself:  would also want to add the appropriate constraints for the gufis

**Comment by nasajoey** [comment]
Closing.  If still buggy, please reopen with details.
