### ISSUE TITLE
Specification around maximum op volume dimensions and time

### ISSUE THREAD

**Issue by boguwei** [nasa/utm-apis#63]
The model requirements specify a maximum dimension and time duration for each operation volume (see [here](https://github.com/nasa/utm-apis/blob/02f4b8b62b5f7c3f07554587ec6e50e098f1c4c9/utm-domains/utm-domain-commons.yaml#L340)). Have these been finalized with specific numbers yet? (asking for TCL4 verification purposes).

**Comment by nasajoey** [comment]
Good question.  Has not been discussed.  I'd say we pick something for now.  6000 ft?  A little less than 1nmi.

**Comment by boguwei** [comment]
@nasajoey sounds like a good number to start with for now. I can put in 6000ft for validation purposes. Any idea on maximum time duration?

**Comment by boguwei** [comment]
@nasajoey follow up question to the first question: what level of precision are we talking about? i.e. what is the minimum number of significant figures acceptable?

**Comment by nasajoey** [comment]
I suggest that being a separate issue for discussion as it may have broader implications.

**Comment by boguwei** [comment]
with respect to which point? the precision or the time duration or both?

**Comment by nasajoey** [comment]
precision should be its own issue.  will try to address duration here at some point.

**Comment by nasajoey** [comment]
let's call duration max at 2 hours.  I don't really know why and wouldn't proffer that for the operational system without discussion.

**Comment by nasajoey** [comment]
closing for now.  but should note to have this discussion in the future.
