### ISSUE TITLE
Model Examples Broken on SwaggerHub

### ISSUE THREAD

**Issue by esparano** [nasa/utm-apis#64]
The example models for the new V4 endpoints seem to be broken.

https://app.swaggerhub.com/apis/utm/uss/v4#/A.%20Required%20Endpoints/put_constraints__message_id_

![image](https://user-images.githubusercontent.com/3947139/42238677-ad14b578-7ecf-11e8-9e7d-9a3730b67721.png)

V3 looked like this for reference:

![image](https://user-images.githubusercontent.com/3947139/42238711-cb2c9a94-7ecf-11e8-8c06-f0b3639e7318.png)

**Comment by nasajoey** [comment]
To summarize for my understanding, this is a swaggerhub bug/issue and not a UTM bug.  Correct?

**Comment by esparano** [comment]
Yeah it's not a very high priority, but it seems to have been fixed already! You guys are fast.

**Comment by issmith1** [comment]
Swagger hub yes.

**Comment by issmith1** [comment]
Fixed via one or both changes: link maintenance within utm-commons, or (likely) swaggerhub site update. Swaggerhub sports v4-draft tip now.
