### ISSUE TITLE
PUT ConstraintMessage Endpoint Inconsistencies

### ISSUE THREAD

**Issue by esparano** [nasa/utm-apis#66]
https://app.swaggerhub.com/apis/utm/uss/v4#/A.%20Required%20Endpoints/put_constraints__message_id_
1) It should read "ConstraintMessage.message_id", not "UTMMessage.message_id" in the description.
2) The example has a "gufi" instead of a "message_id". Edit: To clarify, the model says it should be "message_id".
![image](https://user-images.githubusercontent.com/3947139/42246636-562a1cfa-7eeb-11e8-8da0-c8878e4023b4.png)

**Comment by nasajoey** [comment]
Thanks.  I think fixed in v4-draft-dev branch.  To be merged into v4-draft next sprint.
