### ISSUE TITLE
Constraint Message OriginatorId question

### ISSUE THREAD

**Issue by esparano** [nasa/utm-apis#67]
![image](https://user-images.githubusercontent.com/3947139/42333798-adf539ec-8049-11e8-9c22-dfb78dbe4912.png)

Does uss_id refer to "uss_instance_id" from the UssInstance model?

**Comment by nasajoey** [comment]
I'm going to close this one.  I think the description is about as good as I can make it.  As to the original question, the authorization server doesn't know anything about USS Instances, so it really does mean that we are looking for the name that USSs use to get tokens from the auth server.
