### ISSUE TITLE
Position model time validation

### ISSUE THREAD

**Issue by esparano** [nasa/utm-apis#71]
The Position model states that "time_measured < time_sent MUST be true". Given up to millisecond accuracy, should it be <= instead of strictly less than?

**Comment by nasajoey** [comment]
would love to get one or two more perspectives on this.  Is it feasible/reasonable to have the measurement occur and be sent in the same millisecond?  I'm willing to believe the crowd.

**Comment by esparano** [comment]
It seems as though datetimes may have up to millisecond precision, but they may be sent with as little as one second precision (that's why datetimes can have between 20 and 24 characters, right?...), so in that case I'd definitely say that they could be equal. If not, then as you said we have to figure out whether it's possible that they're the same millisecond.

**Comment by esparano** [comment]
Yeah. I guess those are two separate questions. Whether time_measured and time_sent can be in the same millisecond, and if not, whether second-precision should be allowed for position updates. Let's see if others have some input on this.

**Comment by nasajoey** [comment]
See #81 for some progress(?) here.

**Comment by nasajoey** [comment]
I'll relax this to <= even though I think it opens up for shenanigans.  I know some simulators won't add in that buffer, so that is probably enough reason to relax for now.

**Comment by issmith1** [comment]
what are the use cases for 1-second precision?
