### ISSUE TITLE
JSON Parsing Strictness of Numbers and Bool

### ISSUE THREAD

**Issue by ktian94** [nasa/utm-apis#78]
Opening this issue for tracking future discussion:

How strict should our JSON parsers treat fields encoded as strings that could represent other types? For example, if we receive the JSON object ("altitude": "200.0"} and we're expecting the altitude field to be a double, should we reject with 400 or accept the data? Likewise, if we receive the JSON object {"isRogue": "true"} and we're expecting the isRogue field to be a bool, should we reject with 400 or accept the data?

**Comment by ktian94** [comment]
We've updated our service to be strict, as we've found that once you do allow leniency, there's a whole discussion on what's acceptable and what's not.

**Comment by esparano** [comment]
On a related note, should JSON integers (e.g. 40) be accepted for fields of type double/float? We were thinking that float->int conversion would be disabled because of loss of precision, but int->float would be allowed because there is no loss of precision.

**Comment by rstrauss-logyx** [comment]
These last 2 comments seem good- keep it strict, disallowing booleans, numbers (and structures- e.g. arrays) to be in strings, but int is indeed a subset of double.  Other common causes of bad data are lack of a min length for required, non-empty strings, and specifying there should be no leading or trailing spaces in strings.

**Comment by nasajoey** [comment]
According to RFC8259, there actually is no such thing as an integer type, just number.  The "integer" thing comes from swagger.

So for ints I'd be happy with no quotes (numbers aren't quoted), and any actual integer (no decimal) or a float/double with only zero(es) in the fractional part.

For boolean, I think we need to lay down the law and use unquoted `true` and `false`.

This sounds like the previous comments. Welcome more discussion.

**Comment by mcelhennyi** [comment]
@nasajoey 

`So for ints I'd be happy with no quotes (numbers aren't quoted), and any actual integer (no decimal) or a float/double with only zero(es) in the fractional part.`

I agree with the first part, but not the second part. When the python json decoder gets the 10.0 type number it creates a float type in memory, however when 10 is decoded into memory it creates an integer.


For example,
![image](https://user-images.githubusercontent.com/14264857/44110591-2087b860-9fce-11e8-8201-e259c4e3492f.png)
![image](https://user-images.githubusercontent.com/14264857/44110612-2e5763d2-9fce-11e8-85e3-4e4293354879.png)

So I propose if you are sending an int it MUST be of the form 10, but if you send a float it may be a 10 or a 10.0. 

To add to the other types, I agree on the booleans, numbers and structures having no quotes and that the boolean is either true or false. I agree with @rstrauss-logyx that having empty strings can cause issues.

**Comment by nasajoey** [comment]
Thanks for the input, @mcelhennyi . I'm not super swayed by the Python argument (dynamically typed languages are going to do what they are going to do I suppose), but I am a sucker for super strictness as a rule, and that would help in the example you provide.

If we can get a little more input on the impact to forcing "pure" ints (no decimals at all allowed) from the data generation side, that would be great.  Like, how hard is it to ensure that for int fields that you are not adding decimals?  Hopefully not too hard.  If it is hard, we'll have to see which is harder to deal with.  Reducing garbage-in would probably be my choice.

**Comment by mcelhennyi** [comment]
Something I just came across, similar to this topic of standards...

![image](https://user-images.githubusercontent.com/14264857/44158319-64ac3480-a082-11e8-9b40-88bf18a44cc0.png)

UDC sent me a callback url that is "null" which gets interpreted as a string that is non empty. This seems like a flaw. Simply sending null (without quotes) or nothing at all would be much safer.

See [here](https://stackoverflow.com/questions/21120999/representing-null-in-json)

**Comment by kteneyck** [comment]
@Joey I agree that integer fields must not have a decimal (ex. 5 works but 5.0 fails). 

On a different note I agree with @esparano that int -> float has no loss in precision and the json serializers I've used would require more logic to force 0 to convert to 0.0 for a double field. (ex. 5.0 works and 5 should also work).

**Comment by nasajoey** [comment]
I'm going to try really hard to summarize, but will probably fail.  Please follow on discussion if these rules seem wrong or missed something important:

1. Boolean values must be actual booleans, not enclosed in quotes.  Only `true `or `false` are OK. 
 `"true"` is not OK.
2. numbers in the spec must never be enclosed in quotes.  `123.4` is OK.  `"123.4"` is not OK.
3. fields designated in swagger as integers (integer/int32 or integer/int64) must not have decimals.  `10` is OK, but `10.0` is not OK.
4. fields designated as number/double or number/float may contain a decimal, but don't have to. `10` is OK and so is `10.0`

**Comment by nasajoey** [comment]
@kteneyck @rstrauss-logyx @mcelhennyi @esparano @ktian94 please let me know your thoughts on the above summary.  Would like to close this out if possible.

**Comment by mcelhennyi** [comment]
@nasajoey could you also state a rule for null. 


“Null” vs null vs “” vs (nothing) 

I have seen “null” and that is not very helpful. “”, null, and just no key are my preference. (I am less satisfied with “” but can see why leaving it would be needed/okay)

**Comment by ktian94** [comment]
@nasajoey lgtm, this follows JSON spec. @mcelhennyi I believe [this issue](https://github.com/nasa/utm-apis/issues/65) addresses what you're looking for

**Comment by nasajoey** [comment]
I'm going to close and make this law.  Will end up somewhere... USS Spec or somewhere in API docs someday.  @issmith1 @punamverma @sjurcak please note the four agreed rules above... can make sure we have test coverage in that regard.
