### ISSUE TITLE
Only allow time/date of length 24, must have milliseconds

### ISSUE THREAD

**Issue by rstrauss-logyx** [nasa/utm-apis#81]
This would be easier to validate and accept.

**Comment by nasajoey** [comment]
will add 'pattern' to make this even more solid:

^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]{3})?(Z)$

**Comment by nasajoey** [comment]
update regex to require ms (fractional seconds non-optional):

^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(.[0-9]{3})(Z)$

**Comment by nasajoey** [comment]
This site was helpful for this task:  https://www.regextester.com/94925

**Comment by nasajoey** [comment]
This will probably generate discussion, but closing for now. Expecting comments.
