### ISSUE TITLE
Disprepancy between utm-role.yml and uss-api Swagger.yml

### ISSUE THREAD

**Issue by myspri** [nasa/utm-apis#82]
USS-BASIC scope defines the following scopes
  - utm.nasa.gov_write.operation
  - utm.nasa.gov_write.message
  - utm.nasa.gov_read.constraint
  - utm.nasa.gov_read_uvin
  - utm.nasa.gov_write.conflictmanagement

However GET /operations defines utm.nasa.gov_read.operation.
https://github.com/nasa/utm-apis/blob/v4-draft/uss-api/swagger.yaml

Instead, GET /operation/* needs to be protected using utm.nasa.gov_write.operation.

USS-API needs to be updated to match utm-roles.yml.

**Comment by nasajoey** [comment]
re-assigning to @issmith1 unless she doesn't have time.

**Comment by issmith1** [comment]
duped in JIRA UTM-3605
