### ISSUE TITLE
OperationVolume end time typo?

### ISSUE THREAD

**Issue by esparano** [nasa/utm-apis#92]
In v4-dev-draft, the OperationVolume model in utm-domains/utm-domain-commons.yaml reads

> This value must satisfy: actual_time_end < effective_time_begin whenever actual_time_end is not null.

It seems like that should be a >, based on the provided example times.

**Comment by nasajoey** [comment]
I think the text is correct.  If so, that means we just need to update example values.

Do you see a problem with the requirement as quoted above?

**Comment by esparano** [comment]
I guess I don't understand what actual_time_end is. But yes, the example values should satisfy that requirement.

**Comment by nasajoey** [comment]
an operation can end early.  this field can indicate when that end actually was without altering the original planned end time.

**Comment by nasajoey** [comment]
oops, reopening until fixed.

**Comment by esparano** [comment]
So it can end before the planned start time?

**Comment by esparano** [comment]
I expected either actual_time_end **>** effective_time_begin or actual_time_end < effective_time_**end**

**Comment by sanandk** [comment]
I think it is a typo. The Sprint 0 sheet has this, correctly.
`actual_time_end > effective_time_begin (when actual_time_end is not null)`
Eventhough the operation can end earlier than expected, actual_time_end cannot be less than effective_time_begin.

**Comment by esparano** [comment]
So if it should be 
`actual_time_end > effective_time_begin`

is `actual_time_end <= effective_time_end` something that must be valid? Or can an operation end after it planned to?

**Comment by nasajoey** [comment]
`actual_time_end <= effective_time_end` must be valid if you were conforming during the entirety of your operation.  You may have been non-conforming (or rogue) for some time after `effective_time_end` such that your `actual_time_end` is later.  This is off-nominal... Operators and USSs should endeavor to update plans such that this kind of thing doesn't happen.  But given such possibilities, we don't make it a data validation requirement.

**Comment by esparano** [comment]
Makes sense. Then just swap the < for a > and the examples shouldn't need to be changed anymore. Thanks!!
