### ISSUE TITLE
token with insufficient scope should trigger 403 Forbidden.

### ISSUE THREAD

**Issue by OrangeBean** [nasa/utm-apis#95]
When USS receive token with insufficient scope it should return 403 Forbidden. At the moment uss swagger define only 401 Unauthorized response.

**Comment by issmith1** [comment]
Vijay, I understand you're in this code now, thus assigning.

**Comment by nasajoey** [comment]
Based on the definitions below directly from the relevant, current RFCs, I'd agree that 403 is a more appropriate response when a valid token with the wrong scopes is provided.

### 401 Definition from [RFC7235](https://tools.ietf.org/html/rfc7235#section-3.1):

> The 401 (Unauthorized) status code indicates that the request has not
>    been applied because it lacks valid authentication credentials for
>    the target resource.  The server generating a 401 response MUST send
>    a WWW-Authenticate header field (Section 4.1) containing at least one
>    challenge applicable to the target resource.
> 
>    If the request included authentication credentials, then the 401
>    response indicates that authorization has been refused for those
>    credentials.  The user agent MAY repeat the request with a new or
>    replaced Authorization header field (Section 4.2).  If the 401
>    response contains the same challenge as the prior response, and the
>    user agent has already attempted authentication at least once, then
>    the user agent SHOULD present the enclosed representation to the
>    user, since it usually contains relevant diagnostic information.

### 403 definition from [RFC7231](https://tools.ietf.org/html/rfc7231#section-6.5.3):

> The 403 (Forbidden) status code indicates that the server understood
>    the request but refuses to authorize it.  A server that wishes to
>    make public why the request has been forbidden can describe that
>    reason in the response payload (if any).
> 
>    If authentication credentials were provided in the request, the
>    server considers them insufficient to grant access.  The client
>    SHOULD NOT automatically repeat the request with the same
>    credentials.  The client MAY repeat the request with new or different
>    credentials.  However, a request might be forbidden for reasons
>    unrelated to the credentials.
> 
>    An origin server that wishes to "hide" the current existence of a
>    forbidden target resource MAY instead respond with a status code of
>    404 (Not Found).

**Comment by nasajoey** [comment]
However, I don't think this is a change for Sprint 1.  Let's follow the APIs for now as documented and get this into Sprint 2.

Open to alternate opinions.

**Comment by nasajoey** [comment]
Still agree with this, but kicking can to SPrint 3.
