### ISSUE TITLE
v4-draft - Air speed source shown in Position example but not in Position model requirements

### ISSUE THREAD

**Issue by shabemdadi** [nasa/utm-apis#96]
https://github.com/nasa/utm-apis/blob/7ed648eeadc029b6c971554196e78f3c313f652d/utm-domains/utm-domain-commons.yaml#L997

**Comment by issmith1** [comment]
hi Shabemdadi, as per gh issue #59, " We'd be eliminating the air speed option to simplify data exchange and processing as we haven't seen that field exercised much in our demonstrations." 

This is apparently an error in the example data but I will double check its status.  
Thank you for your input. 
Irene

**Comment by sjurcak** [comment]
Hi Shabemdadi, 
The fix for this has now been pushed to v4-draft.
Commit # 28adb14294459b81a972b0a865d220e94d7ae982
Thanks,
Sherry
