### ISSUE TITLE
Example constraint message does not contain fields “permitted_uas” and “permitted_gufis”

### ISSUE THREAD

**Issue by HarryAirMap** [nasa/utm-apis#98]
In the schema definition https://raw.githubusercontent.com/nasa/utm-apis/v4-draft/utm-domains/utm-domain-commons.yaml#/definitions/ConstraintMessage, the two fields “permitted_uas” and “permitted_gufis” are defined in the schema, but are not present in the example. It is clarified that they are required.

**Comment by nasajoey** [comment]
I think done.  If wrong, please let me know.

**Comment by HarryAirMap** [comment]
The change was at the branch "v4-draft-dev". I think you need to merge it to "v4-draft".

**Comment by nasajoey** [comment]
Yes, the merge will happen when we "pin" our version of the API for the Sprint 2 sim... v4-draft will be the truth... this is like staging in v4-draft-dev.  All key changes will come at once in that merge.

Thanks for keeping an eye on this though!
