### ISSUE TITLE
ConstraintMessage Altitudes Not Required?

### ISSUE THREAD

**Issue by esparano** [nasa/utm-apis#99]
A ConstraintMessage's constraint_geography field is required (which is a 2D GeoJSON Polygon), but the min_altitude and max_altitude fields are not marked as required. Is this a typo in the docs? If not, does omitting a min or max (or both) altitude signal that the constraint extends "infinitely" in that direction? Or something like that?

**Comment by nasajoey** [comment]
Done.  They are required now.  Thanks!
